---
title: "grepreaper Tests"
author: "David Shilane"
date: "2025-08-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Package Basics

```{r }
library(data.table)
library(grepreaper)
```

## File Reading {.tabset}

### Basics



```{r }
grep_read(files = "C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv")
```



```{r }
grep_read(files = "C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv", show_cmd = T)
```


These tests pass.

### Multiple Files {.tabset}

#### No File Name, No Line Number -- NEEDS REVISION

```{r }
dat <- grep_read(files = c("C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv", "C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv"), show_line_numbers = F, include_filename = F)
dat[1:2,]
```

Note that the **carat** variable is now NA.

```{r }
dat[, mean(is.na(carat))]
```

#### No File Name, But Line Number Included -- NEEDS REVISION

```{r }
dat <- grep_read(files = c("C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv", "C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv"), show_line_numbers = T, include_filename = F)
dat[1:2,]
dat[, sum(is.na(carat))]
```


#### Includes File Name, But No Line Number Included -- PASSES TEST

```{r }
dat <- grep_read(files = c("C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv", "C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv"), show_line_numbers = F, include_filename = T)
dat[1:2,]
dat[, sum(is.na(carat))]
```

#### Includes File Name and Line Number -- PASSES TEST

```{r }
dat <- grep_read(files = c("C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv", "C:\\Users\\Atharv Raskar\\Desktop\\grepreaper\\data\\diamonds.csv"), show_line_numbers = T, include_filename = T)
dat[1:2,]
dat[, sum(is.na(carat))]
```
