---
title: "grepreaper Tests"
author: "David Shilane"
date: "2025-08-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Package Basics

```{r }
library(data.table)
library(grepreaper)
```

## File Reading


```{r }
grep_read(files = "~/Downloads/diamonds.csv")
```



```{r }
grep_read(files = "~/Downloads/diamonds.csv", show_cmd = T)
```


Noted issues:

When reading from multiple files and showing the line numbers, we have an issue with losing the **carat** column's values:

```{r }
dat <- grep_read(files = c("~/Downloads/diamonds.csv", "~/Downloads/diamonds.csv"), show_line_numbers = T)
dat[1:2,]
```

Note that header rows have not been removed:

```{r }
dat[is.na(carat),]
```

We can remove rows with line_number == 1:

```{r }
dat <- dat[line_number != 1,]
```

Then we could also renumber the lines so that headers do not count:

```{r }
dat[, line_number := line_number - 1]
```

Those steps would reasonably handle this error.

```{r }
dat[1:2,]
```